### ISSUE TITLE
README.md contains Carthage link to original repository, which maybe is a different implementation than this one

### ISSUE THREAD

**Issue by avanderberg** [WeltN24/SwiftFilePath#1]
The file README.md contains the text:

```
Carthage
To install it, simply add the following line to your Cartfile:
github "nori0620/SwiftFilePath"
```

The original repository maybe has a different implementation than this repository. I suggest either updating the Carthage link, or change the text to clarify which version will be installed with this link.

**Comment by vittoriom** [comment]
Hi Alex, thanks for reporting! 
To make it easier for us to maintain the code in sync with the original repo and to possibly contribute through pull requests, I think it's better to keep the README.md file unchanged, but good catch nevertheless!

If it's fine for you, I would close this issue
